### ISSUE TITLE
blog post URL correction

### ISSUE THREAD

**Issue by shivtorov** [greiginsydney/New-OoklaSpeedTest.ps1#1]
https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/blob/8cc6c20413863c007c335f307adf635f8d55e92f/New-OoklaSpeedTest.ps1#L17

I guess the URL should be updated to https://greiginsydney.com/new-ooklaspeedtest-ps1/

**Comment by greiginsydney** [comment]
Thanks Mike. Fixed.
