### ISSUE TITLE
Script misuses pathing

### ISSUE THREAD

**Issue by cjramseyer** [greiginsydney/New-OoklaSpeedTest.ps1#10]
A typical user is going to install the Ookla speedtest in the default directory.
That directory is: C:\Program Files\Speedtest

The program should NOT be installed in the PRTG directory.
The script can't find speedtest.exe otherwise.  The exe is not the only piece necessary.

Please add the default pathing and create a parameter to provide a different path to the speedtest exe

**Comment by greiginsydney** [comment]
@cjramseyer, the ZIP I'm downloading from the [OOKLA CLI link](https://www.speedtest.net/apps/cli) only contains an EXE and MD files, no installer.

Can you link me to the version you're installing?

\- G.
