### ISSUE TITLE
GDPR Consent

### ISSUE THREAD

**Issue by Fi-5** [greiginsydney/New-OoklaSpeedTest.ps1#2]
When executed, the speedtest.exe requires GDPR consent. It remembers it within user security context under which it was executed. Unfortunately, PRTG context is different from normal user.
There is a flag to accept GDPR.
To fix this, change line 147 to

$params = '--accept-gdpr '

I am not sure about legal consequences, but this is the only way I managed to get it working.

**Comment by OzRocky** [comment]
It seems that the extra GDPR requirement only comes up if you are in the EU, hence we completely missed it here in the land of Oz.  :-)

I suspect that GDPR would insist that the user has to accept Ookla's Privacy Agreement, so we probably need to come up with a way of alerting users in the EU about this requirement. 

In the meantime, you can append **--accept-gdpr** to line 177:

`$params += "--format=json --precision=$($precision) --accept-license --accept-gdpr 2>&1"`

This of course assumes that you have agreed to Oookla's Privacy Policy at [https://www.speedtest.net/about/privacy](https://www.speedtest.net/about/privacy) We'll add the Ookla URL's to the top of the code to alert users to them. 

Both **--accept-license** and **--accept-gdpr** really only need to run once by PRTG for it to stick, but it doesn't seem to matter if they remain. 

r.

**Comment by greiginsydney** [comment]
Close with merge #3
