### ISSUE TITLE
XML PE233/PE231 Error

### ISSUE THREAD

**Issue by timracer** [greiginsydney/New-OoklaSpeedTest.ps1#7]
Hi! I got XML: The returned XML does not match the expected schema. (code: PE233) — JSON: The returned JSON does not match the expected structure (No mapping for the Unicode character exists in the target multi-byte code page). (code: PE231)"" error. All group policies are been edited. What could be wrong?

**Comment by greiginsydney** [comment]
Hi Tim,

I've not seen that error before.

Can you dig a little further into PRTG's sensor logs and see if there's a file there with some more useful debugging info?

Check out the folder `C:\ProgramData\Paessler\PRTG Network Monitor\Logs\sensors` & sort by date modified. 

&nbsp;<br>

\- Greig.

**Comment by timracer** [comment]
Sorry, that i didn't mention before but there's no Logs folder. I've enabled Write result to disk in case of error but no any Logs folder, then I tried using "-debug" parameter but still no “New-OoklaSpeedTest-yyyyMMM.log” file in the same folder

**Comment by timracer** [comment]
Here is the list

![image](https://user-images.githubusercontent.com/6567906/188595020-9c95e8ff-bd2e-41c2-9f60-7c70bb69a558.png)

**Comment by timracer** [comment]
In C:\ProgramData\Paessler\PRTG Network Monitor\Logs\sensors just  MomoCore.log
[MomoCore.log](https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/files/9495159/MomoCore.log)

**Comment by timracer** [comment]
Should I use any Windows credentials in the sensor settings?

**Comment by timracer** [comment]
I'm using prtg 22.3 on windows server 2012

**Comment by greiginsydney** [comment]
OK, apparently there's a switch we need to throw first. Under Devices and the Sensor, in the Sensor's Settings, change "Result Handling" to "Store Result":

![image](https://user-images.githubusercontent.com/11004787/188598164-b62ea052-b0e3-40a8-9649-a6e92a9e3831.png)

THAT will hopefully create a log file with a useful error message.

(I referenced that in [the more detailed blog post](https://greiginsydney.com/new-ooklaspeedtest-ps1/), although it looks like the wording of the Sensor options has changed slightly since that was written. Have you seen that or are you just going on the ReadMe here on GitHub?)

---------------

In the meantime, what happens if you run the script from a PowerShell Window first? Whatever output that spits should better help us understand what's going wrong.

`.\New-OoklaSpeedTest.ps1`

Add the -AcceptGdpr switch if that's relevant to you.

**Comment by timracer** [comment]
Here is some log by prtg 
[Result of Sensor 4286.Data.txt](https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/files/9495343/Result.of.Sensor.4286.Data.txt)

**Comment by timracer** [comment]
Here's one more file
[Result of Sensor 4286.log](https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/files/9495395/Result.of.Sensor.4286.log)

**Comment by greiginsydney** [comment]
Ahhh. Bingo.

You don't have a clean version of the script. You have what looks like an HTML scrape of it.

**Comment by greiginsydney** [comment]
Check this out:
https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/issues/4#issuecomment-745606893

Your other option is to use the "raw" button, which WILL give you a clean version to scrape.

![image](https://user-images.githubusercontent.com/11004787/188602148-754664e3-11bc-4e23-8413-695cebb51d65.png)


\- G.

**Comment by timracer** [comment]
I've created a new sensor with proper script file and now it returns just "error"
[Result of Sensor 4288.txt](https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/files/9495560/Result.of.Sensor.4288.txt)
[Result of Sensor 4288.log](https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/files/9495561/Result.of.Sensor.4288.log)

**Comment by timracer** [comment]
Logfile
[New-OoklaSpeedTest-2022сен.log](https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/files/9495594/New-OoklaSpeedTest-2022.log)

**Comment by greiginsydney** [comment]
"Cannot read from socket" suggests a network problem. There's no response from Speedtest?

Navigate to "C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\" and run SpeedTest.exe

**Comment by timracer** [comment]
I don't know what happen, 
![image](https://user-images.githubusercontent.com/6567906/188612255-273362d9-88c9-4073-8fdb-2ef542314b17.png)

Thank you for helping. If I wanna use server id 6386 where should I define this? In the sensor setting "Parameter" input like -ServerID=6386?

**Comment by greiginsydney** [comment]
The correct syntax for that is `-ServerId nnnn`.

**Comment by timracer** [comment]
Thank you!
