### ISSUE TITLE
Still getting an XML error. 

### ISSUE THREAD

**Issue by enaoumtft** [greiginsydney/New-OoklaSpeedTest.ps1#9]
<?xml version="1.0" encoding="UTF-8"?><prtg><error>1</error><text>error</text></prtg>

Result of Debug:
Apr12-0919 Output file is     "C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\OoklaSpeedTest.xml"
Apr12-0919 Speedtest found at "C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\Speedtest.exe"
Apr12-0919 Params   = "--format=json --precision=1 --accept-license 2>&1)"
Apr12-0919 Response = 
Apr12-0919 Retrying
Apr12-0919 Response = 
Apr12-0919 Retrying
Apr12-0919 Response = 
Apr12-0919 Retrying
Apr12-0919 Exited cleanly.

**Comment by greiginsydney** [comment]
What do you get if you just run speedtest from the commandline?

```
cd "C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML"
.\Speedtest.exe --format=json --precision=1 --accept-license 2>&1
```

Here's mine:
![image](https://user-images.githubusercontent.com/11004787/231605139-347a65f4-fd63-4ddc-a277-456a8054c05d.png)

Hopefully any error there will guide you to the resolution.


\- G.

**Comment by enaoumtft** [comment]
It just runs speedtest app without connecting to a server. it just sits there waiting for manual input to click go. 
I think it has something to do with the speedtest app itself as I am running a windows server and can't get it from MS Store. I had to download an older msi off the web. I tried a couple of versions with no luck.

**Comment by greiginsydney** [comment]
Try it without any of the command line parameters:

```
cd "C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML"
.\Speedtest.exe
```

The `2>&1` might be masking something you need to see, like the need for the GDPR switch.
